[tool.poetry]
name = "it-mentor"
version = "0.1.0"
description = ""
authors = ["Alexander Altukhov <sasha@littlebox.spb.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
